---
galaxy_info:
  author: Richard Sessa
  description: Configuración declarativa e idempotente de OSPFv2 en RouterOS.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: RouterOS
      versions:
        - all
dependencies: []
