---
galaxy_info:
  author: Richard Sessa
  description: Restauración controlada y segura de copias de seguridad en RouterOS.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: RouterOS
      versions:
        - all
dependencies: []
