---
galaxy_info:
  author: Richard Sessa
  description: Despliegue declarativo de túneles GRE con cifrado IPsec en RouterOS.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: RouterOS
      versions:
        - all
dependencies: []
