---
galaxy_info:
  author: Richard Sessa
  description: Extracción automatizada y segura de copias de seguridad (.rsc y .backup) en RouterOS.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: RouterOS
      versions:
        - all
dependencies: []
